version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  webapp:
    build: app
    image: webapp
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=kengkkun
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
    depends_on:
      - db